language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - pypy
services:
  - memcached
install: python setup.py install
before_script: pip install -r test-requirements.txt
script:
  - flake8
  - nosetests
